POST http://localhost:3000/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5kdDI3MDkwNSIsImlkIjoiNjU4OWFhYjlkNWY4MjI1MGRhY2IzZWVjIiwiaWF0IjoxNzAzNTQwNjQyLCJleHAiOjE3MDM1NDQyNDJ9.QwugII993dvcMa9WyFBJjdb9eQSxJ3kDpmvI8e81IMg

{   
  "title": "Harry Potter",
  "author": "J.K.Rowling",
  "url": "harrypotter",
  "likes": 1000
}