POST http://localhost:3000/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5kdDI3MDkwNSIsImlkIjoiNjU4OWFhYjlkNWY4MjI1MGRhY2IzZWVjIiwiaWF0IjoxNzAzNTM3NTYyLCJleHAiOjE3MDM1NDExNjJ9.65QTr7FnJ7kKICBsp4k34vBi_4CLP4Bk-8zBRnfeTQ8

{   
  "title": "Harry Potter",
  "author": "J.K.Rowling",
  "url": "harrypotter",
  "likes": 1000
}