POST http://localhost:3000/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5kdDI3MDkwNSIsImlkIjoiNjU4OWFhYjlkNWY4MjI1MGRhY2IzZWVjIiwiaWF0IjoxNzAzNTIyMDU0LCJleHAiOjE3MDM1MjU2NTR9.JAp8j29YCa_RaebwoherTFCCMKi1PiALLRGU6yqoQNk

{   
  "title": "Harry Potter",
  "author": "J.K.Rowling",
  "url": "harrypotter",
  "likes": 1000
}